import './globals.css'
import { Nunito } from 'next/font/google'
import VerticalMenu from "@/app/componentes/navbar";
import DropdownHandler from "@/app/componentes/navbar";
import {Header} from "@/app/componentes/header";
import Script from 'next/script'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <>
      <Script src="https://www.google.com/recaptcha/api.js" async defer />
    </>
      <body>
      <DropdownHandler></DropdownHandler>
      <Header></Header>
      <div className="p-8">
          {children}
      </div>


      </body>
    </html>
  )
}
